services:
  timescaledb:
    image: timescale/timescaledb:2.14.2-pg15
    container_name: mini_scada_db
    restart: always
    env_file:
      - .env.prod
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: UTC
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mini_scada_mqtt
    restart: always
    ports:
      # 외부 MQTT 포트가 필요 없으면 1883은 공개하지 않는 것이 좋음
      # - "1883:1883"

      # Nginx에서 MQTT WebSocket 프록시용
      - "18095:9001"
    volumes:
      - ./infra/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-t", "$$SYS/broker/uptime", "-C", "1"]
      interval: 10s
      timeout: 5s
      retries: 5

  simulator:
    build:
      context: ./simulator
      dockerfile: Dockerfile
    container_name: mini_scada_simulator
    restart: unless-stopped
    expose:
      - "5020"
    environment:
      MODBUS_PORT: 5020
      TZ: UTC
    command: python app/simulator.py

  backend:
    image: ${BACKEND_IMAGE:-mini-scada-backend:latest}
    build:
        context: ./backend
        dockerfile: Dockerfile
    container_name: mini_scada_backend
    restart: always
    env_file:
      - .env.prod
    environment:
        SPRING_PROFILES_ACTIVE: prod
        DB_HOST: timescaledb
        DB_PORT: 5432
        MQTT_HOST: mosquitto
        MQTT_PORT: 1883
        MQTT_WS_PORT: 9001
        TZ: UTC
    ports:
        - "18094:8080"
    depends_on:
        - timescaledb
        - mosquitto
  
  frontend:
    image: ${FRONTEND_IMAGE:-mini-scada-frontend:latest}
    build:
        context: ./frontend
        dockerfile: Dockerfile
    container_name: mini_scada_frontend
    restart: always
    environment:
      VITE_PROXY_TARGET: http://backend:8080
      VITE_MQTT_PROXY_TARGET: http://mosquitto:9001
      VITE_MQTT_WS_URL: wss://scada.swsung72.site/mqtt
    ports:
        - "18093:5173"
    depends_on:
        - backend

volumes:
  timescaledb_data: