-- Mini SCADA baseline schema (TimescaleDB). Extension is created by infra init script.

CREATE TABLE roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(255) UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE user_roles (
    user_id UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id INTEGER NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, role_id)
);

CREATE INDEX idx_user_roles_user ON user_roles (user_id);
CREATE INDEX idx_user_roles_role ON user_roles (role_id);

CREATE TABLE system_data_policy (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    raw_retention_days INTEGER NOT NULL,
    aggregate_retention_days INTEGER NOT NULL,
    downsampling_interval VARCHAR(32) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_sdp_raw CHECK (raw_retention_days >= 1),
    CONSTRAINT chk_sdp_agg CHECK (aggregate_retention_days >= 1)
);

CREATE TABLE devices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(150) NOT NULL,
    code VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    protocol_type VARCHAR(20) NOT NULL DEFAULT 'MODBUS_TCP',
    ip_address VARCHAR(64),
    port INTEGER,
    slave_id INTEGER,
    polling_interval_sec INTEGER NOT NULL DEFAULT 5,
    timeout_ms INTEGER NOT NULL DEFAULT 2000,
    retry_count INTEGER NOT NULL DEFAULT 3,
    offline_threshold_sec INTEGER NOT NULL DEFAULT 15,
    status VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN',
    last_seen_at TIMESTAMPTZ,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_devices_protocol CHECK (protocol_type IN ('MODBUS_TCP', 'MODBUS_RTU', 'SIMULATOR')),
    CONSTRAINT chk_devices_status CHECK (status IN ('ONLINE', 'OFFLINE', 'UNKNOWN', 'DISABLED')),
    CONSTRAINT chk_polling_interval CHECK (polling_interval_sec >= 1),
    CONSTRAINT chk_timeout_ms CHECK (timeout_ms > 0),
    CONSTRAINT chk_retry CHECK (retry_count >= 0),
    CONSTRAINT chk_offline_threshold CHECK (offline_threshold_sec >= 1)
);

CREATE INDEX idx_devices_active ON devices (is_active);

CREATE TABLE device_tags (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    device_id UUID NOT NULL REFERENCES devices (id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    tag_type VARCHAR(30) NOT NULL DEFAULT 'CUSTOM',
    function_code INTEGER NOT NULL,
    address INTEGER NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    data_type VARCHAR(30) NOT NULL,
    byte_order VARCHAR(20),
    unit VARCHAR(30),
    scale_factor NUMERIC(18, 6) NOT NULL DEFAULT 1.0,
    offset_value NUMERIC(18, 6) NOT NULL DEFAULT 0.0,
    warning_min NUMERIC(18, 6),
    warning_max NUMERIC(18, 6),
    critical_min NUMERIC(18, 6),
    critical_max NUMERIC(18, 6),
    deadband NUMERIC(18, 6),
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (device_id, code),
    UNIQUE (device_id, function_code, address),
    CONSTRAINT chk_device_tags_fc CHECK (function_code IN (1, 2, 3, 4)),
    CONSTRAINT chk_device_tags_addr CHECK (address >= 0),
    CONSTRAINT chk_device_tags_qty CHECK (quantity >= 1),
    CONSTRAINT chk_device_tags_dtype CHECK (data_type IN (
        'BOOL', 'INT16', 'UINT16', 'INT32', 'UINT32', 'FLOAT32'
    ))
);

CREATE INDEX idx_device_tags_device ON device_tags (device_id);

CREATE TABLE device_tag_latest (
    tag_id UUID PRIMARY KEY REFERENCES device_tags (id) ON DELETE CASCADE,
    device_id UUID NOT NULL REFERENCES devices (id) ON DELETE CASCADE,
    value_numeric NUMERIC(24, 8),
    value_text VARCHAR(255),
    quality VARCHAR(20) NOT NULL DEFAULT 'GOOD',
    alarm_state VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    collected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_dtl_quality CHECK (quality IN ('GOOD', 'BAD', 'UNCERTAIN', 'TIMEOUT')),
    CONSTRAINT chk_dtl_alarm CHECK (alarm_state IN ('NORMAL', 'WARNING', 'CRITICAL', 'UNKNOWN'))
);

CREATE INDEX idx_device_tag_latest_device ON device_tag_latest (device_id);

CREATE TABLE tag_readings (
    time TIMESTAMPTZ NOT NULL,
    tag_id UUID NOT NULL REFERENCES device_tags (id) ON DELETE CASCADE,
    device_id UUID NOT NULL REFERENCES devices (id) ON DELETE CASCADE,
    value_numeric NUMERIC(24, 8),
    value_text VARCHAR(255),
    quality VARCHAR(20) NOT NULL DEFAULT 'GOOD',
    alarm_state VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    raw_payload JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (time, tag_id),
    CONSTRAINT chk_tr_quality CHECK (quality IN ('GOOD', 'BAD', 'UNCERTAIN', 'TIMEOUT')),
    CONSTRAINT chk_tr_alarm CHECK (alarm_state IN ('NORMAL', 'WARNING', 'CRITICAL', 'UNKNOWN'))
);

SELECT create_hypertable('tag_readings', 'time', if_not_exists => TRUE);

CREATE INDEX idx_tag_readings_tag_time ON tag_readings (tag_id, time DESC);
CREATE INDEX idx_tag_readings_device_time ON tag_readings (device_id, time DESC);
