package com.example.miniscada.common.exception;

public enum ErrorCode {
    UNAUTHORIZED,
    FORBIDDEN,
    INVALID_CREDENTIALS,
    USER_INACTIVE,
    RESOURCE_NOT_FOUND,
    DEVICE_NOT_FOUND,
    ALARM_NOT_FOUND,
    TAG_NOT_FOUND,
    INVALID_DATE_RANGE,
    INVALID_INPUT,
    INVALID_REQUEST,
    USERNAME_TAKEN,
    EMAIL_TAKEN,
    INVALID_POLICY,
    DEVICE_DUPLICATED,
    DEVICE_IN_USE,
    TAG_DUPLICATED,
    TAG_REFERENCED,
    CONNECTION_TEST_FAILED
}
